cx: !!python/object/apply:numpy.core.multiarray.scalar
- &id001 !!python/object/apply:numpy.dtype
  args:
  - f8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  cqET+hALdEA=
cy: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  hD74TtZ9aEA=
fx: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  jetblPC6l0A=
fy: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  kvE7SgnIl0A=
k1: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  6ko2WO/h8D8=
k2: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  N6KlGId9bUA=
lens: pinhole
p1/k3: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  gzzLqB8ynT8=
p2/k4: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  z0r3mlMWiT8=
